# Make heatmaps for the large scale simulations and recognize the tendency of simulation by the number of accetable samples in each grid
library(ggplot2)
library(reshape2)
# Through switch the name of csv files to make the heatmaps for both Hepadnaviridae simualtion and Retroviridae simualtion
#Different conditions would belong to different locations in the dataframe from the csv file.
# 25 leaves group
H <- read.csv("HepadnaviridaeTableFinalS25.csv")
Hs25co0 <- H[1:7]
names(Hs25co0) <- swg
Hs25co0$hc <- hcg
# the necessary format of dataframe for making heatmap by ggplot2
Hs25co0 <- melt(Hs25co0)
# give a label to recognize these elements are owned by cospecaition = 0
Hs25co0 <- cbind(Hs25co0, rep(c("co0"),36))
names(Hs25co0)[4] <- "co"

Hs25co2 <- H[c(1,8:13)]
names(Hs25co2) <- swg
Hs25co2$hc <- hcg
Hs25co2 <- melt(Hs25co2)
Hs25co2 <- cbind(Hs25co2, rep(c("co2"),36))
names(Hs25co2)[4] <- "co" 
Hs25 <- rbind(Hs25co0,Hs25co2)

Hs25co4 <- H[c(1,14:19)]
names(Hs25co4) <- swg
Hs25co4$hc <- hcg
Hs25co4 <- melt(Hs25co4)
Hs25co4 <- cbind(Hs25co4, rep(c("co4"),36))
names(Hs25co4)[4] <- "co" 
Hs25 <- rbind(Hs25, Hs25co4)

Hs25co6 <- H[c(1,20:25)]
names(Hs25co6) <- swg
Hs25co6$hc <- hcg
Hs25co6 <- melt(Hs25co6)
Hs25co6 <- cbind(Hs25co6, rep(c("co6"),36))
names(Hs25co6)[4] <- "co" 
Hs25 <- rbind(Hs25, Hs25co6)

Hs25co8 <- H[c(1,26:31)]
names(Hs25co8) <- swg
Hs25co8$hc <- hcg
Hs25co8 <- melt(Hs25co8)
Hs25co8 <- cbind(Hs25co8, rep(c("co8"),36))
names(Hs25co8)[4] <- "co" 
Hs25 <- rbind(Hs25, Hs25co8)

Hs25co1 <- H[c(1,32:37)]
names(Hs25co1) <- swg
Hs25co1$hc <- hcg
Hs25co1 <- melt(Hs25co1)
Hs25co1 <- cbind(Hs25co1, rep(c("co1"),36))
names(Hs25co1)[4] <- "co" 
Hs25 <- rbind(Hs25, Hs25co1)
Hs25 <- cbind(Hs25, rep(c("s25")))
names(Hs25)[5] <- "s"

# Group 100
H <- read.csv("HepadnaviridaeTableFinals100.csv")
Hs100co0 <- H[c(1:7)]
names(Hs100co0) <- swg
Hs100co0$hc <- hcg
Hs100co0 <- melt(Hs100co0)
Hs100co0 <- cbind(Hs100co0, rep(c("co0"),36))
names(Hs100co0)[4] <- "co" 

Hs100co2 <- H[c(1,8:13)]
names(Hs100co2) <- swg
Hs100co2$hc <- hcg
Hs100co2 <- melt(Hs100co2)
Hs100co2 <- cbind(Hs100co2, rep(c("co2"),36))
names(Hs100co2)[4] <- "co"
Hs100 <- rbind(Hs100co0, Hs100co2)

Hs100co4 <- H[c(1,14:19)]
names(Hs100co4) <- swg
Hs100co4$hc <- hcg
Hs100co4 <- melt(Hs100co4)
Hs100co4 <- cbind(Hs100co4, rep(c("co4"),36))
names(Hs100co4)[4] <- "co" 
Hs100 <- rbind(Hs100, Hs100co4)
Hs100co6 <- H[c(1,20:25)]
names(Hs100co6) <- swg
Hs100co6$hc <- hcg
Hs100co6 <- melt(Hs100co6)
Hs100co6 <- cbind(Hs100co6, rep(c("co6"),36))
names(Hs100co6)[4] <- "co" 
Hs100 <- rbind(Hs100, Hs100co6)

Hs100co8 <- H[c(1,26:31)]
names(Hs100co8) <- swg
Hs100co8$hc <- hcg
Hs100co8 <- melt(Hs100co8)
Hs100co8 <- cbind(Hs100co8, rep(c("co8"),36))
names(Hs100co8)[4] <- "co" 
Hs100 <- rbind(Hs100, Hs100co8)

Hs100co1 <- H[c(1,32:37)]
names(Hs100co1) <- swg
Hs100co1$hc <- hcg
Hs100co1 <- melt(Hs100co1)
Hs100co1 <- cbind(Hs100co1, rep(c("co1"),36))
names(Hs100co1)[4] <- "co" 
Hs100 <- rbind(Hs100, Hs100co1)
Hs100 <- cbind(Hs100, rep(c("s100")))
names(Hs100)[5] <- "s"

# 200 Group
H <- read.csv("HepadnaviridaeTableFinalS200.csv")
Hs200co0 <- H[c(1:7)]
names(Hs200co0) <- swg
Hs200co0$hc <- hcg
Hs200co0 <- melt(Hs200co0)
Hs200co0 <- cbind(Hs200co0, rep(c("co0"),36))
names(Hs200co0)[4] <- "co" 

Hs200co2 <- H[c(1,8:13)]
names(Hs200co2) <- swg
Hs200co2$hc <- hcg
Hs200co2 <- melt(Hs200co2)
Hs200co2 <- cbind(Hs200co2, rep(c("co2"),36))
names(Hs200co2)[4] <- "co"
Hs200 <- rbind(Hs200co0, Hs200co2)

Hs200co4 <- H[c(1,14:19)]
names(Hs200co4) <- swg
Hs200co4$hc <- hcg
Hs200co4 <- melt(Hs200co4)
Hs200co4 <- cbind(Hs200co4, rep(c("co4"),36))
names(Hs200co4)[4] <- "co" 
Hs200 <- rbind(Hs200, Hs200co4)

Hs200co6 <- H[c(1,20:25)]
names(Hs200co6) <- swg
Hs200co6$hc <- hcg
Hs200co6 <- melt(Hs200co6)
Hs200co6 <- cbind(Hs200co6, rep(c("co6"),36))
names(Hs200co6)[4] <- "co" 
Hs200 <- rbind(Hs200, Hs200co6)

Hs200co8 <- H[c(1,26:31)]
names(Hs200co8) <- swg
Hs200co8$hc <- hcg
Hs200co8 <- melt(Hs200co8)
Hs200co8 <- cbind(Hs200co8, rep(c("co8"),36))
names(Hs200co8)[4] <- "co" 
Hs200 <- rbind(Hs200, Hs200co8)

Hs200co1 <- H[c(1,32:37)]
names(Hs200co1) <- swg
Hs200co1$hc <- hcg
Hs200co1 <- melt(Hs200co1)
Hs200co1 <- cbind(Hs200co1, rep(c("co1"),36))
names(Hs200co1)[4] <- "co" 
Hs200 <- rbind(Hs200, Hs200co1)
Hs200 <- cbind(Hs200, rep(c("s200")))
names(Hs200)[5] <- "s"
H <- rbind(Hs25,Hs100,Hs200)

# The whole heatmaps generated by ggplot2
HHM <- ggplot(data = H, aes(x = variable, y = hc,fill=value)) +
  scale_fill_gradientn(colours =colorRampPalette(colour)(100)) +
  geom_tile() + labs(x = "Host Switch", y="Host Choosing", title = "", fill = "") +
  facet_grid(s~co)
HHM
# only 25 heatmap for Hepadnaviridae required in report
H25 <- H[which(H$s == "s25"),]
# exclude hs = 1
H25 <- H25[which(H25$variable != "sw1"),]
H25
HM25 <- ggplot(data = H25, aes(x = variable, y = hc,fill=value)) +
  scale_fill_gradientn(colours =colorRampPalette(colour)(100)) +
  geom_tile() + labs(x = "Host Switch", y="Host Choosing", title = "", fill = "") +
  facet_grid(s~co)
HM25

# only 100 heatmap for Hepadnaviridae required in report 
H100 <- H[which(H$s == "s100"),]
# exclude hs = 1
H100 <- H100[which(H100$variable != "sw1"),]
H100
HM100 <- ggplot(data = H100, aes(x = variable, y = hc,fill=value)) +
  scale_fill_gradientn(colours =colorRampPalette(colour)(100)) +
  geom_tile() + labs(x = "Host Switch", y="Host Choosing", title = "", fill = "") +
  facet_grid(s~co)
HM100
